// Generated by Wrangler by running `wrangler types`

interface Env {
  PASSWORD: string;
  DurableDatabase: DurableObjectNamespace<
    import("./src/index").DurableDatabase
  >;
  jakebrown_blog: R2Bucket;
  ASSETS: Fetcher;
}
declare module "*.sql" {
  const value: string;
  export default value;
}
