name = "jakebrown"
compatibility_date = "2025-01-03"
compatibility_flags = [ "nodejs_compat" ]
main = "src/index.tsx"

routes = [
  { pattern = "www.jakebrown.net", custom_domain = true }
]

[[rules]] 
type = "Text"
globs = ["**/*.sql"]
fallthrough = true

[[durable_objects.bindings]]
name = "DurableDatabase"
class_name = "DurableDatabase"

[assets]
directory = "public"
binding = "ASSETS"

[[r2_buckets]]
bucket_name = "jakebrown-blog"
preview_bucket_name = "jakebrown-blog"
binding = "jakebrown_blog"

[observability]
enabled = true

[[migrations]]
tag = "<v1>"
new_sqlite_classes = ["MyDurableObject"] 

[[migrations]]
tag = "v3"
new_sqlite_classes = ["DurableDatabase"]

[[migrations]]
tag = "removeMyDurableObject"
deleted_classes = ["MyDurableObject"] 