name = "jakebrown"
compatibility_date = "2025-01-03"
compatibility_flags = [ "nodejs_compat" ]
main = "src/index.tsx"

routes = [
  { pattern = "www.jakebrown.net", custom_domain = true }
]

[assets]
directory = "public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "blog"
id = "3e8ab6dc7df54c09ac677a7c1175d2fd"
preview_id = "3e8ab6dc7df54c09ac677a7c1175d2fd"

[[r2_buckets]]
bucket_name = "jakebrown-blog"
preview_bucket_name = "jakebrown-blog"
binding = "jakebrown_blog"

[observability]
enabled = true