name = "jakebrown"
compatibility_date = "2025-01-03"
compatibility_flags = [ "nodejs_compat" ]
main = "src/index.tsx"

routes = [
  { pattern = "www.jakebrown.net", custom_domain = true }
]

[assets]
directory = "public"
binding = "ASSETS"

[[r2_buckets]]
bucket_name = "jakebrown-blog"
preview_bucket_name = "jakebrown-blog"
binding = "jakebrown_blog"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "jakebrown.net"
database_id = "6c21fae9-2f6e-4a21-8661-249979f72052"