name = "jakebrown"
main = "./workers/app.ts"
compatibility_date = "2025-01-01"
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "SESSION"
id = "245892257160427483f8c5ac3837c822"

[[kv_namespaces]]
binding = "CACHE" 
id = "b477a170064c4c398572ab5a09dd2424"

[observability]
enabled = true
